Basic Pytorch

In [0]:
import torch

x= torch.rand(3)

In [2]:
print(x)

tensor([0.9181, 0.5966, 0.3178])


In [3]:
torch.cuda.is_available()

False

In [4]:
#empty tensor
x = torch.empty(2,3)
x

tensor([[7.3401e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [0]:
 x = torch.rand(2,2)

In [6]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [7]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [8]:
x = torch.ones(2,2,dtype=torch.int)
x.dtype

torch.int32

In [9]:
x = torch.ones(2,2,dtype=torch.double)
x.dtype

torch.float64

In [10]:
x = torch.ones(2,2,dtype=torch.float16)
x.dtype

torch.float16

In [11]:
x.size()

torch.Size([2, 2])

In [12]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.7983, 0.1339],
        [0.3994, 0.6033]])
tensor([[0.6447, 0.0109],
        [0.6600, 0.8870]])


Operations

In [13]:
z = x + y
z

tensor([[1.4430, 0.1448],
        [1.0594, 1.4903]])

In [14]:
#or
torch.add(x,y)

tensor([[1.4430, 0.1448],
        [1.0594, 1.4903]])

In [15]:
#inplace
y.add_(x)

tensor([[1.4430, 0.1448],
        [1.0594, 1.4903]])

In [16]:
x -y

tensor([[-0.6447, -0.0109],
        [-0.6600, -0.8870]])

In [17]:
torch.sub(x,y)

tensor([[-0.6447, -0.0109],
        [-0.6600, -0.8870]])

In [18]:
x.sub_(y)

tensor([[-0.6447, -0.0109],
        [-0.6600, -0.8870]])

In [19]:
x*y

tensor([[-0.9303, -0.0016],
        [-0.6993, -1.3219]])

In [20]:
torch.mul(x,y)

tensor([[-0.9303, -0.0016],
        [-0.6993, -1.3219]])

In [21]:
y.mul_(x)

tensor([[-0.9303, -0.0016],
        [-0.6993, -1.3219]])

In [22]:
x/y

tensor([[0.6930, 6.9080],
        [0.9439, 0.6710]])

In [23]:
torch.div(x,y)

tensor([[0.6930, 6.9080],
        [0.9439, 0.6710]])

In [24]:
x.div_(y)

tensor([[0.6930, 6.9080],
        [0.9439, 0.6710]])

In [25]:
x = torch.rand(5,3)
x

tensor([[0.7191, 0.3088, 0.7626],
        [0.3946, 0.6164, 0.9305],
        [0.4462, 0.5365, 0.0884],
        [0.2932, 0.3775, 0.9297],
        [0.7728, 0.3319, 0.9065]])

Transformation

In [26]:
x[:,0]

tensor([0.7191, 0.3946, 0.4462, 0.2932, 0.7728])

In [27]:
x[1,1]

tensor(0.6164)

In [28]:
#actual value
x[1,1].item()

0.6163697242736816

In [29]:
x=torch.rand(4,4)
x

tensor([[0.7760, 0.0621, 0.0549, 0.3143],
        [0.8360, 0.3516, 0.4567, 0.1362],
        [0.3643, 0.6684, 0.8201, 0.1660],
        [0.5098, 0.6236, 0.0025, 0.4908]])

Re-sizing

In [30]:
x.view(-1,8)

tensor([[0.7760, 0.0621, 0.0549, 0.3143, 0.8360, 0.3516, 0.4567, 0.1362],
        [0.3643, 0.6684, 0.8201, 0.1660, 0.5098, 0.6236, 0.0025, 0.4908]])

In [31]:
x.view(-1,8).size()

torch.Size([2, 8])

torch => np

In [0]:
import numpy as np

In [0]:
a = torch.ones(5)
a
b = a.numpy()

In [34]:
print(b)

[1. 1. 1. 1. 1.]


In [35]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [36]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

np => torch

In [0]:
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [38]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [39]:
x = torch.ones(5,requires_grad = True)
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)